### ISSUE TITLE
setting it up

### ISSUE THREAD

**Issue by Umair-khalidkhan** [robinrowe/libunistd#7]
Hi! I downloaded it and added the master file to the additional library directories of my dll/project and added the file path in the following SS. but still getting errors. help would be appreciated

**Comment by Umair-khalidkhan** [comment]
<img width="928" alt="uni" src="https://user-images.githubusercontent.com/42065308/121775459-4c95f000-cba1-11eb-8a79-7b5ab909d701.PNG">

**Comment by robinrowe** [comment]
The error message says it. Do not include Windows.h before including unistd.h. You show unistd.h as the first include in your file. That implies whatever is including your file had already included Windows.h somewhere else. Find that and put #include <unistd.h> ahead of it. 

Libunistd.h insists on being first because it includes Winsock.h. That needs to come first before including Windows.h due to an annoying quirk of Windows header file include order from the early days when Windows network support was optional. Including Winsock.h first changes what Windows.h defines.

**Comment by Umair-khalidkhan** [comment]
Hi! The only file I found to be using Windows.h is your own unistd.h,
Windows.h is not included in any other header.

**Comment by robinrowe** [comment]
It has to be. That Windows.h has already been defined is what is triggering the error. Some other header is including Windows.h before unistd.h. Many Windows headers include Windows.h. Try including unistd.h in your binapp_utils.cpp file before any other header. Try only compiling the .cpp file having issues, not doing an overall build. It can help to look at the output window, not the error window, that sometimes the messages there are better insight.

**Comment by robinrowe** [comment]
Not an error. This warning is to protect users from inadvertently including Windows.h before unistd.h, and thereby having the wrong Winsock config.
